### ISSUE TITLE
newESX Error

### ISSUE THREAD

**Issue by Luderas** [smallo92/xnVending#4]
NewESX
SCRIPT ERROR: @es_extended/server/classes/player.lua:280: attempt to index a nil value (field '?')
> ref (@es_extended/server/classes/player.lua:280)
> ref (@xnVending/server/server.lua:22)
> TriggerServerCallback (@es_extended/server/functions.lua:142)
> handler (@es_extended/server/common.lua:83)

and if i use ESX
SCRIPT ERROR: @xnVending/server/server.lua:34: attempt to index a nil value (local 'targetItem')
> TriggerServerCallback (@es_extended/server/functions.lua:142)
> handler (@es_extended/server/common.lua:83)

**Comment by smallo92** [comment]
You not having the items in your database isn't an error. Try adding them to your items table.
