### ISSUE TITLE
Weed Vending Machine .ytyp

### ISSUE THREAD

**Issue by Mooreiche** [smallo92/xnVending#6]
Hey there, Smallo! I really wanted to say thank you for the Standalone Version. It really makes the game so much more immersive. 

However, i tried to place the Weed Vending Machine but there is no .ymap included and it seems that Codewalker wont do anything with that .ytyp file which is included. Maybe the File is corrupt or iam just an Idiot.

Again, thank you for your work and time. Greetings from Germany to Australia :)

**Comment by smallo92** [comment]
> iam just an Idiot.

It's that one

**Comment by Mooreiche** [comment]
alright, i will look into it. Thx again dude

**Comment by Mooreiche** [comment]
> > iam just an Idiot.
> 
> It's that one

alright, i will look into it. Thx again dude
